// var img=document.getElementsByTagName('img');
// alert(img.length);
// alert(img[0].src);
// alert(img.item(0).src);
// alert(img.namedItem('img1'));
// alert(img['img1']);
// var all=document.getElementsByTagName('*');
// alert(all.length);
// var t=document.getElementsByName('ttt');
// alert(t.namedItem(''));
// alert(document.anchors.length);
// alert(document.forms.length);
alert(document.images.length);
